<?php
 if (isset($_SESSION["addproduct"])) {
?>
<?php
 $output = '<script type="text/javascript"  data-cfasync="false">';
  
    $output .= 'var timecheck =  setInterval(function() { if (typeof userengage == "function") { ';
    $output .= "userengage('event.addToCart', {" .
               "'sku': '" . $_SESSION["productData"]["sku"] . 
               "','name': '" . $_SESSION["productData"]["name"] . 
               "','price': '" . $_SESSION["productData"]["price"] . 
               "','quantity': '" . $_SESSION["productData"]["quantity"] . 
               "' });";
    $output .= ' clearInterval(timecheck);} },500);';
    $output .= ' </script>';
    echo $output;
}
unset($_SESSION["addproduct"]);
unset($_SESSION["productData"]);

if (isset($_SESSION["userRegistered"])) {
    
    $om = \Magento\Framework\App\ObjectManager::getInstance();  
$customerSession = $om->get('Magento\Customer\Model\Session'); 

$customerData = $customerSession->getCustomer()->getData();
    $output = '<script type="text/javascript"  data-cfasync="false">';
    $output .= 'var timecheck =  setInterval(function() { if (typeof userengage == "function") { ';
    $output .= "userengage('event.registration', {" .
               "'id': '" . $customerData["entity_id"] . 
               "','fullname': '" . $customerData["firstname"] .' '.$customerData["lastname"] .
               "','email': '" . $customerData["email"] . 
               "' });";
    $output .= ' clearInterval(timecheck);} },500);';
    $output .= ' </script>';
    echo $output;

    unset($_SESSION["userRegistered"]);
}

if (isset($_SESSION["orderCreated"])) {
	$orderId = $_SESSION["checkout"]["last_order_id"];
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$order = $objectManager->create('Magento\Sales\Model\Order')->load($orderId); 
    $data = "'id': '".$order->getIncrementId() ."'," .
            "'shipping': '" . $order->getShippingAmount() ."'," .
            "'tax': '" . $order->getTaxAmount() . "'," .
            "'coupon': '" . $order->getCouponCode() . "'," .
            "'revenue': '" . $order->getGrandTotal() . "'";
	$output = ' <script type="text/javascript"  data-cfasync="false">';	   	
    $output .= 'var timecheck =  setInterval(function() { if (typeof userengage == "function") { ';
    $output .= "userengage('event.purchase', {".$data."});";
    $output .= ' clearInterval(timecheck);} },500);';
    $output .= ' </script>';
    echo $output;
    unset($_SESSION["orderCreated"]);   
}
?>
